package com.example.imagesearchapp.api

import com.example.imagesearchapp.BuildConfig
import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.Query


// for declare some method later that generated by retrofit
interface UnsplashApi {

    //static variable in kotlin
    companion object {
        const val API_KEY = BuildConfig.UNSPLASH_ACCESS_KEY
        const val BASE_URL = "https://api.unsplash.com"
    }

    @Headers("Accept-version: v1", "Authorization: Client-ID $API_KEY")
    @GET("/search/photos")
    suspend fun searchPhotos(

        //value has to match the parameter name
        @Query("query") query: String,
        @Query("page") page: Int,
        @Query("per_page") perPage: Int,
    ): UnsplashResponse
}